draft update jetbrains-release

diff --git a/.github/workflows/jetbrains-release.yaml b/.github/workflows/jetbrains-release.yaml
--- a/.github/workflows/jetbrains-release.yaml
+++ b/.github/workflows/jetbrains-release.yaml
@@ -3,13 +3,21 @@
 # See https://plugins.jetbrains.com/docs/intellij/plugin-signing.html for more information.
 
 name: Release
-# on:
-#   release:
-#     types: [prereleased, released]
+
+on:
+  create:
+    tags:
+      - "v0.0.*-jetbrains"
+    branches:
+      - dev
 
 defaults:
   run:
     working-directory: ./extensions/intellij
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
 
 jobs:
   check_release_name:
@@ -41,6 +49,10 @@ jobs:
         with:
           ref: ${{ github.event.release.tag_name }}
 
+      # Validate wrapper
+      - name: Gradle Wrapper Validation
+        uses: gradle/actions/wrapper-validation@v3
+
       # Set up Java environment for the next steps
       - name: Setup Java
         uses: actions/setup-java@v4
@@ -59,14 +71,19 @@ jobs:
         id: properties
         shell: bash
         run: |
-          CHANGELOG="$(cat << 'EOM' | sed -e 's/^[[:space:]]*$//g' -e '/./,$!d'
-          ${{ github.event.release.body }}
-          EOM
-          )"
+          PROPERTIES="$(./gradlew properties --console=plain -q)"
+          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
+          # CHANGELOG="$(./gradlew getChangelog --unreleased --no-header --console=plain -q)"
+          CHANGELOG=""
+
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+          echo "pluginVerifierHomeDir=~/.pluginVerifier" >> $GITHUB_OUTPUT
 
           echo "changelog<<EOF" >> $GITHUB_OUTPUT
           echo "$CHANGELOG" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
+
+          ./gradlew listProductsReleases # prepare list of IDEs for Plugin Verifier
 
       # Setup Node.js
       - name: Use Node.js from .nvmrc
@@ -100,7 +117,7 @@ jobs:
           npm ci
 
       # npm install binary
-      - name: Install core node_modules
+      - name: Install binary node_modules
         run: |
           cd ../../binary
           npm ci
@@ -123,60 +140,344 @@ jobs:
           cd ../../extensions/vscode
           npm ci
           npm run prepackage
+        env:
+          # https://github.com/microsoft/vscode-ripgrep/issues/9#issuecomment-643965333
+          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
 
       # Build binaries
-      - name: Install core node_modules
+      - name: Build the binaries
         run: |
           cd ../../binary
           npm run build
 
-      # Update Unreleased section with the current release note
-      - name: Patch Changelog
-        if: ${{ steps.properties.outputs.changelog != '' }}
-        env:
-          CHANGELOG: ${{ steps.properties.outputs.changelog }}
+      # Build plugin
+      - name: Build plugin
+        run: ./gradlew buildPlugin
+
+      # Prepare plugin archive content for creating artifact
+      - name: Prepare Plugin Artifact
+        id: artifact
+        shell: bash
         run: |
-          ./gradlew patchChangelog --release-note="$CHANGELOG"
+          cd ../../extensions/intellij/build/distributions
+          FILENAME=`ls *.zip`
+          unzip "$FILENAME" -d content
 
-      # Upload artifact as a release asset
-      - name: Upload Release Asset
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*
+          echo "filename=${FILENAME%.????}" >> $GITHUB_OUTPUT
 
-      # Publish the plugin to JetBrains Marketplace
-      - name: Publish Plugin
-        env:
-          PUBLISH_TOKEN: ${{ secrets.JETBRAINS_PUBLISH_TOKEN }}
-          CERTIFICATE_CHAIN: ${{ secrets.JETBRAINS_CERTIFICATE_CHAIN }}
-          PRIVATE_KEY: ${{ secrets.JETBRAINS_PRIVATE_KEY }}
-          PRIVATE_KEY_PASSWORD: ${{ secrets.JETBRAINS_PRIVATE_KEY_PASSWORD }}
-        run: ./gradlew publishPlugin
+      # Store already-built plugin as an artifact for downloading
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ steps.artifact.outputs.filename }}
+          path: ./extensions/intellij/build/distributions/content/*/*
 
-      # Create a pull request
-      - name: Create Pull Request
-        if: ${{ steps.properties.outputs.changelog != '' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # Upload binaries as artifacts
+      - name: Upload artifact (darwin-arm64)
+        uses: actions/upload-artifact@v4
+        with:
+          name: continue-binary-darwin-arm64
+          path: ./binary/bin/darwin-arm64/
+
+      - name: Upload artifact (darwin-x64)
+        uses: actions/upload-artifact@v4
+        with:
+          name: continue-binary-darwin-x64
+          path: ./binary/bin/darwin-x64/
+
+      - name: Upload artifact (win32-x64)
+        uses: actions/upload-artifact@v4
+        with:
+          name: continue-binary-win32-x64
+          path: ./binary/bin/win32-x64/
+
+      - name: Upload artifact (linux-arm64)
+        uses: actions/upload-artifact@v4
+        with:
+          name: continue-binary-linux-arm64
+          path: ./binary/bin/linux-arm64/
+
+      - name: Upload artifact (linux-x64)
+        uses: actions/upload-artifact@v4
+        with:
+          name: continue-binary-linux-x64
+          path: ./binary/bin/linux-x64/
+
+  test-binaries:
+    needs: build
+    strategy:
+      matrix:
+        include:
+          - os: windows-latest
+            platform: win32
+            arch: x64
+            npm_config_arch: x64
+          - os: ubuntu-latest
+            platform: linux
+            arch: x64
+            npm_config_arch: x64
+          # arm64 not actually supported by GitHub
+          # - os: ubuntu-latest
+          #   platform: linux
+          #   arch: arm64
+          #   npm_config_arch: arm64
+          - os: macos-12
+            platform: darwin
+            arch: x64
+            npm_config_arch: x64
+          - os: macos-latest
+            platform: darwin
+            arch: arm64
+            npm_config_arch: arm64
+    runs-on: ${{ matrix.os }}
+    steps:
+      # 1. Check-out repository
+      - name: Check-out repository
+        uses: actions/checkout@v4
+
+      # 2. Install npm dependencies
+      - name: Use Node.js from .nvmrc
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: ".nvmrc"
+
+      - name: Cache core node_modules
+        uses: actions/cache@v3
+        with:
+          path: core/node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('core/package-lock.json') }}
+
+      - name: Cache binary node_modules
+        uses: actions/cache@v3
+        with:
+          path: binary/node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('binary/package-lock.json') }}
+
+      - name: Install Core Dependencies
         run: |
-          VERSION="${{ github.event.release.tag_name }}"
-          BRANCH="changelog-update-$VERSION"
-          LABEL="release changelog"
+          cd ../../core
+          npm ci
 
-          git config user.email "action@github.com"
-          git config user.name "GitHub Action"
+      - name: Install Binary Dependencies
+        run: |
+          cd ../../binary
+          npm ci
 
-          git checkout -b $BRANCH
-          git commit -am "Changelog update - $VERSION"
-          git push --set-upstream origin $BRANCH
+      # Download the binary artifact
+      - name: Download binary artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: continue-binary-${{ matrix.platform }}-${{ matrix.arch }}
+          path: ./binary/bin/${{ matrix.platform }}-${{ matrix.arch }}/
 
-          gh label create "$LABEL" \
-            --description "Pull requests with release changelog update" \
-            --force \
-            || true
+      # Set execute permissions for the binary (non-Windows)
+      - name: Set execute permissions
+        run: |
+          cd ../../binary/bin/${{ matrix.platform }}-${{ matrix.arch }}
+          chmod +x continue-binary
+          chmod +x node_sqlite3.node
+          chmod +x index.node
+          chmod +x esbuild
+        if: ${{ matrix.platform }} != 'win32'
 
-          gh pr create \
-            --title "Changelog update - \`$VERSION\`" \
-            --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
-            --label "$LABEL" \
-            --head $BRANCH
+      - name: Copy node_sqlite3.node to necessary location
+        run: |
+          cd ../../binary
+          mkdir build
+          cp ./bin/${{ matrix.platform }}-${{ matrix.arch }}/node_sqlite3.node ./build/node_sqlite3.node
+
+      # Run tests for binary
+      - name: Run binary tests
+        run: |
+          cd ../../binary
+          npm run test
+
+      - name: Upload logs
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: core-logs-${{ matrix.platform }}-${{ matrix.arch }}
+          path: binary/.continue/logs/core.log
+
+  # Run tests and upload a code coverage report
+  test:
+    name: Test
+    needs: [build]
+    runs-on: ubuntu-latest
+    steps:
+      # Check out current repository
+      - name: Fetch Sources
+        uses: actions/checkout@v4
+
+      # Set up Java environment for the next steps
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: zulu
+          java-version: 17
+
+      # Setup Gradle
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v3
+        with:
+          gradle-home-cache-cleanup: true
+
+      # Run tests
+      - name: Run Tests
+        run: ./gradlew check
+
+      # Collect Tests Result of failed tests
+      - name: Collect Tests Result
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: tests-result
+          path: ${{ github.workspace }}/extensions/intellij/build/reports/tests
+
+      # Upload the Kover report to CodeCov
+      # - name: Upload Code Coverage Report
+      #   uses: codecov/codecov-action@v4
+      #   with:
+      #     files: ${{ github.workspace }}/build/reports/kover/report.xml
+
+  # Run Qodana inspections and provide report
+  inspectCode:
+    if: false
+    name: Inspect code
+    needs: [build]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      checks: write
+      pull-requests: write
+    steps:
+      # Free GitHub Actions Environment Disk Space
+      - name: Maximize Build Space
+        uses: jlumbroso/free-disk-space@main
+        with:
+          tool-cache: false
+          large-packages: false
+
+      # Check out current repository
+      - name: Fetch Sources
+        uses: actions/checkout@v4
+
+      # Set up Java environment for the next steps
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: zulu
+          java-version: 17
+
+      # Run Qodana inspections
+      - name: Qodana - Code Inspection
+        uses: JetBrains/qodana-action@v2024.1.5
+        with:
+          cache-default-branch-only: true
+
+  # Run plugin structure verification along with IntelliJ Plugin Verifier
+  verify:
+    name: Verify plugin
+    needs: [build]
+    runs-on: ubuntu-latest
+    steps:
+      # Free GitHub Actions Environment Disk Space
+      - name: Maximize Build Space
+        uses: jlumbroso/free-disk-space@main
+        with:
+          tool-cache: false
+          large-packages: false
+
+      # Check out current repository
+      - name: Fetch Sources
+        uses: actions/checkout@v4
+
+      # Set up Java environment for the next steps
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: zulu
+          java-version: 17
+
+      # Setup Gradle
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v3
+        with:
+          gradle-home-cache-cleanup: true
+
+      # Cache Plugin Verifier IDEs
+      - name: Setup Plugin Verifier IDEs Cache
+        uses: actions/cache@v4
+        with:
+          path: ${{ needs.build.outputs.pluginVerifierHomeDir }}/ides
+          key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}
+
+      # Run Verify Plugin task and IntelliJ Plugin Verifier tool
+      - name: Run Plugin Verification tasks
+        run: ./gradlew runPluginVerifier -Dplugin.verifier.home.dir=${{ needs.build.outputs.pluginVerifierHomeDir }}
+
+      # Collect Plugin Verifier Result
+      - name: Collect Plugin Verifier Result
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: pluginVerifier-result
+          path: ${{ github.workspace }}/build/reports/pluginVerifier
+
+  upload-release:
+    # # Update Unreleased section with the current release note
+    # - name: Patch Changelog
+    #   if: ${{ steps.properties.outputs.changelog != '' }}
+    #   env:
+    #     CHANGELOG: ${{ steps.properties.outputs.changelog }}
+    #   run: |
+    #     ./gradlew patchChangelog --release-note="$CHANGELOG"
+
+    - name: Download the plugin
+      uses: actions/download-artifact@v4
+       with:
+         name: ${{ steps.artifact.outputs.filename }}
+         path: ./build/distributions/
+
+    # Upload artifact as a release asset
+    - name: Upload Release Asset
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*
+
+    # Publish the plugin to JetBrains Marketplace
+    - name: Publish Plugin
+      env:
+        PUBLISH_TOKEN: ${{ secrets.JETBRAINS_PUBLISH_TOKEN }}
+        CERTIFICATE_CHAIN: ${{ secrets.JETBRAINS_CERTIFICATE_CHAIN }}
+        PRIVATE_KEY: ${{ secrets.JETBRAINS_PRIVATE_KEY }}
+        PRIVATE_KEY_PASSWORD: ${{ secrets.JETBRAINS_PRIVATE_KEY_PASSWORD }}
+      run: ./gradlew publishPlugin
+
+    # Create a pull request
+    - name: Create Pull Request
+      if: ${{ steps.properties.outputs.changelog != '' }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        VERSION="${{ github.event.release.tag_name }}"
+        BRANCH="changelog-update-$VERSION"
+        LABEL="release changelog"
+
+        git config user.email "action@github.com"
+        git config user.name "GitHub Action"
+
+        git checkout -b $BRANCH
+        git commit -am "Changelog update - $VERSION"
+        git push --set-upstream origin $BRANCH
+
+        gh label create "$LABEL" \
+          --description "Pull requests with release changelog update" \
+          --force \
+          || true
+
+        gh pr create \
+          --title "Changelog update - \`$VERSION\`" \
+          --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
+          --label "$LABEL" \
+          --head $BRANCH
